"""Initial schema - all tables

Revision ID: 71cb064b86a1
Revises: 
Create Date: 2026-01-29 08:35:16.575395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71cb064b86a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('user_ip', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_table_record', 'audit_log', ['table_name', 'record_id'], unique=False)
    op.create_index(op.f('ix_audit_log_record_id'), 'audit_log', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_log_table_name'), 'audit_log', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_user_name'), 'audit_log', ['user_name'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('credit_days', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_code'), 'customers', ['code'], unique=True)
    op.create_index(op.f('ix_customers_is_active'), 'customers', ['is_active'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_table('slitting_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.String(length=50), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('coil_width', sa.Float(), nullable=False),
    sa.Column('total_coil_weight', sa.Float(), nullable=False),
    sa.Column('scrap_mm', sa.Float(), nullable=True),
    sa.Column('scrap_weight', sa.Float(), nullable=True),
    sa.Column('raw_materials_json', sa.Text(), nullable=False),
    sa.Column('slit_details_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slitting_plans_plan_id'), 'slitting_plans', ['plan_id'], unique=True)
    op.create_index(op.f('ix_slitting_plans_status'), 'slitting_plans', ['status'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('vendor_type', sa.String(length=50), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vendors_type', 'vendors', ['vendor_type'], unique=False)
    op.create_index(op.f('ix_vendors_code'), 'vendors', ['code'], unique=True)
    op.create_index(op.f('ix_vendors_is_active'), 'vendors', ['is_active'], unique=False)
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_table('weight_receipt_drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_card_number', sa.String(length=50), nullable=False),
    sa.Column('design_index', sa.Integer(), nullable=False),
    sa.Column('actual_weight', sa.Float(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('design_deduction', sa.Float(), nullable=True),
    sa.Column('receipt_sets', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wrd_job_design', 'weight_receipt_drafts', ['job_card_number', 'design_index'], unique=False)
    op.create_index(op.f('ix_weight_receipt_drafts_job_card_number'), 'weight_receipt_drafts', ['job_card_number'], unique=False)
    op.create_index(op.f('ix_weight_receipt_drafts_timestamp'), 'weight_receipt_drafts', ['timestamp'], unique=False)
    op.create_table('coils',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coil_number', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('thickness', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('coating', sa.String(length=50), nullable=True),
    sa.Column('total_weight', sa.Float(), nullable=False),
    sa.Column('used_weight', sa.Float(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('coil_supplier', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('po_number', sa.String(length=50), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('rm_age_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint('total_weight >= 0', name='check_coil_total_weight'),
    sa.CheckConstraint('used_weight >= 0', name='check_coil_used_weight'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_coils_grade', 'coils', ['grade'], unique=False)
    op.create_index(op.f('ix_coils_coil_number'), 'coils', ['coil_number'], unique=True)
    op.create_index(op.f('ix_coils_grade'), 'coils', ['grade'], unique=False)
    op.create_index(op.f('ix_coils_location'), 'coils', ['location'], unique=False)
    op.create_index(op.f('ix_coils_status'), 'coils', ['status'], unique=False)
    op.create_index(op.f('ix_coils_width'), 'coils', ['width'], unique=False)
    op.create_table('delivery_challans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('challan_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('challan_date', sa.Date(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('total_gross_weight', sa.Float(), nullable=True),
    sa.Column('total_deduction', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint('total_gross_weight >= 0', name='check_dc_gross_weight'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_challans_challan_date'), 'delivery_challans', ['challan_date'], unique=False)
    op.create_index(op.f('ix_delivery_challans_challan_number'), 'delivery_challans', ['challan_number'], unique=True)
    op.create_index(op.f('ix_delivery_challans_customer_id'), 'delivery_challans', ['customer_id'], unique=False)
    op.create_index(op.f('ix_delivery_challans_status'), 'delivery_challans', ['status'], unique=False)
    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_card_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('po_no', sa.String(length=50), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('hole_size', sa.Integer(), nullable=True),
    sa.Column('number_of_cores', sa.Integer(), nullable=True),
    sa.Column('header_core_stack', sa.Float(), nullable=True),
    sa.Column('rate_per_kg', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('total_design_weight', sa.Float(), nullable=True),
    sa.Column('total_allocated_weight', sa.Float(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint('delivery_date >= order_date', name='check_delivery_after_order'),
    sa.CheckConstraint('total_design_weight >= 0', name='check_total_design_weight'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_orders_delivery_date'), 'sales_orders', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_sales_orders_is_deleted'), 'sales_orders', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sales_orders_job_card_number'), 'sales_orders', ['job_card_number'], unique=True)
    op.create_index(op.f('ix_sales_orders_order_date'), 'sales_orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_sales_orders_status'), 'sales_orders', ['status'], unique=False)
    op.create_table('material_allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('coil_id', sa.Integer(), nullable=False),
    sa.Column('weight_allocated', sa.Float(), nullable=False),
    sa.Column('allocation_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint('weight_allocated > 0', name='check_allocation_weight'),
    sa.ForeignKeyConstraint(['coil_id'], ['coils.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_allocations_allocation_date'), 'material_allocations', ['allocation_date'], unique=False)
    op.create_index(op.f('ix_material_allocations_coil_id'), 'material_allocations', ['coil_id'], unique=False)
    op.create_index(op.f('ix_material_allocations_sales_order_id'), 'material_allocations', ['sales_order_id'], unique=False)
    op.create_table('sales_order_designs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('mm_stack', sa.Float(), nullable=True),
    sa.Column('thickness', sa.Float(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('pieces', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('material_type', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('hole_type', sa.String(length=50), nullable=True),
    sa.Column('coating', sa.String(length=50), nullable=True),
    sa.Column('party_job_no', sa.String(length=50), nullable=True),
    sa.Column('fm_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('sets > 0', name='check_design_sets'),
    sa.CheckConstraint('weight >= 0', name='check_design_weight'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_designs_width', 'sales_order_designs', ['width'], unique=False)
    op.create_index(op.f('ix_sales_order_designs_material_type'), 'sales_order_designs', ['material_type'], unique=False)
    op.create_index(op.f('ix_sales_order_designs_sales_order_id'), 'sales_order_designs', ['sales_order_id'], unique=False)
    op.create_table('weight_receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('job_card_number', sa.String(length=50), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('party_name', sa.String(length=200), nullable=True),
    sa.Column('po_number', sa.String(length=50), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('design_details_json', sa.Text(), nullable=False),
    sa.Column('weight_entry_type', sa.String(length=50), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('total_weight', sa.Float(), nullable=False),
    sa.Column('deduction', sa.Float(), nullable=True),
    sa.Column('production_status', sa.String(length=30), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint('deduction >= 0', name='check_wr_deduction'),
    sa.CheckConstraint('total_weight >= 0', name='check_wr_total_weight'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_receipts_job_card_number'), 'weight_receipts', ['job_card_number'], unique=False)
    op.create_index(op.f('ix_weight_receipts_receipt_date'), 'weight_receipts', ['receipt_date'], unique=False)
    op.create_index(op.f('ix_weight_receipts_receipt_number'), 'weight_receipts', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_weight_receipts_sales_order_id'), 'weight_receipts', ['sales_order_id'], unique=False)
    op.create_table('finished_goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('weight_receipt_id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('job_card_number', sa.String(length=50), nullable=True),
    sa.Column('weight_receipt_number', sa.String(length=50), nullable=True),
    sa.Column('party_name', sa.String(length=200), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('fg_qty', sa.Float(), nullable=False),
    sa.Column('despatched_qty', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('fg_date', sa.Date(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint('despatched_qty >= 0', name='check_despatched_qty'),
    sa.CheckConstraint('fg_qty >= 0', name='check_fg_qty'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.ForeignKeyConstraint(['weight_receipt_id'], ['weight_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finished_goods_job_card_number'), 'finished_goods', ['job_card_number'], unique=False)
    op.create_index(op.f('ix_finished_goods_sales_order_id'), 'finished_goods', ['sales_order_id'], unique=False)
    op.create_index(op.f('ix_finished_goods_status'), 'finished_goods', ['status'], unique=False)
    op.create_index(op.f('ix_finished_goods_weight_receipt_id'), 'finished_goods', ['weight_receipt_id'], unique=False)
    op.create_table('delivery_challan_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('challan_id', sa.Integer(), nullable=False),
    sa.Column('weight_receipt_id', sa.Integer(), nullable=False),
    sa.Column('finished_goods_id', sa.Integer(), nullable=False),
    sa.Column('job_card_number', sa.String(length=50), nullable=True),
    sa.Column('po_number', sa.String(length=50), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('gross_weight', sa.Float(), nullable=False),
    sa.Column('deduction', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('gross_weight > 0', name='check_dci_gross_weight'),
    sa.ForeignKeyConstraint(['challan_id'], ['delivery_challans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finished_goods_id'], ['finished_goods.id'], ),
    sa.ForeignKeyConstraint(['weight_receipt_id'], ['weight_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_challan_items_challan_id'), 'delivery_challan_items', ['challan_id'], unique=False)
    op.create_index(op.f('ix_delivery_challan_items_finished_goods_id'), 'delivery_challan_items', ['finished_goods_id'], unique=False)
    op.create_index(op.f('ix_delivery_challan_items_weight_receipt_id'), 'delivery_challan_items', ['weight_receipt_id'], unique=False)
    op.create_table('finished_goods_transfers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transfer_number', sa.String(length=50), nullable=False),
    sa.Column('finished_goods_id', sa.Integer(), nullable=False),
    sa.Column('job_card_number', sa.String(length=50), nullable=True),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('from_location', sa.String(length=50), nullable=False),
    sa.Column('to_location', sa.String(length=50), nullable=False),
    sa.Column('transfer_type', sa.String(length=50), nullable=True),
    sa.Column('quantity_transferred', sa.Float(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint('from_location != to_location', name='check_different_locations'),
    sa.CheckConstraint('quantity_transferred > 0', name='check_transfer_qty'),
    sa.ForeignKeyConstraint(['finished_goods_id'], ['finished_goods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fgt_from', 'finished_goods_transfers', ['from_location'], unique=False)
    op.create_index('idx_fgt_to', 'finished_goods_transfers', ['to_location'], unique=False)
    op.create_index(op.f('ix_finished_goods_transfers_finished_goods_id'), 'finished_goods_transfers', ['finished_goods_id'], unique=False)
    op.create_index(op.f('ix_finished_goods_transfers_transfer_date'), 'finished_goods_transfers', ['transfer_date'], unique=False)
    op.create_index(op.f('ix_finished_goods_transfers_transfer_number'), 'finished_goods_transfers', ['transfer_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finished_goods_transfers_transfer_number'), table_name='finished_goods_transfers')
    op.drop_index(op.f('ix_finished_goods_transfers_transfer_date'), table_name='finished_goods_transfers')
    op.drop_index(op.f('ix_finished_goods_transfers_finished_goods_id'), table_name='finished_goods_transfers')
    op.drop_index('idx_fgt_to', table_name='finished_goods_transfers')
    op.drop_index('idx_fgt_from', table_name='finished_goods_transfers')
    op.drop_table('finished_goods_transfers')
    op.drop_index(op.f('ix_delivery_challan_items_weight_receipt_id'), table_name='delivery_challan_items')
    op.drop_index(op.f('ix_delivery_challan_items_finished_goods_id'), table_name='delivery_challan_items')
    op.drop_index(op.f('ix_delivery_challan_items_challan_id'), table_name='delivery_challan_items')
    op.drop_table('delivery_challan_items')
    op.drop_index(op.f('ix_finished_goods_weight_receipt_id'), table_name='finished_goods')
    op.drop_index(op.f('ix_finished_goods_status'), table_name='finished_goods')
    op.drop_index(op.f('ix_finished_goods_sales_order_id'), table_name='finished_goods')
    op.drop_index(op.f('ix_finished_goods_job_card_number'), table_name='finished_goods')
    op.drop_table('finished_goods')
    op.drop_index(op.f('ix_weight_receipts_sales_order_id'), table_name='weight_receipts')
    op.drop_index(op.f('ix_weight_receipts_receipt_number'), table_name='weight_receipts')
    op.drop_index(op.f('ix_weight_receipts_receipt_date'), table_name='weight_receipts')
    op.drop_index(op.f('ix_weight_receipts_job_card_number'), table_name='weight_receipts')
    op.drop_table('weight_receipts')
    op.drop_index(op.f('ix_sales_order_designs_sales_order_id'), table_name='sales_order_designs')
    op.drop_index(op.f('ix_sales_order_designs_material_type'), table_name='sales_order_designs')
    op.drop_index('idx_designs_width', table_name='sales_order_designs')
    op.drop_table('sales_order_designs')
    op.drop_index(op.f('ix_material_allocations_sales_order_id'), table_name='material_allocations')
    op.drop_index(op.f('ix_material_allocations_coil_id'), table_name='material_allocations')
    op.drop_index(op.f('ix_material_allocations_allocation_date'), table_name='material_allocations')
    op.drop_table('material_allocations')
    op.drop_index(op.f('ix_sales_orders_status'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_order_date'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_job_card_number'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_is_deleted'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_delivery_date'), table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_index(op.f('ix_delivery_challans_status'), table_name='delivery_challans')
    op.drop_index(op.f('ix_delivery_challans_customer_id'), table_name='delivery_challans')
    op.drop_index(op.f('ix_delivery_challans_challan_number'), table_name='delivery_challans')
    op.drop_index(op.f('ix_delivery_challans_challan_date'), table_name='delivery_challans')
    op.drop_table('delivery_challans')
    op.drop_index(op.f('ix_coils_width'), table_name='coils')
    op.drop_index(op.f('ix_coils_status'), table_name='coils')
    op.drop_index(op.f('ix_coils_location'), table_name='coils')
    op.drop_index(op.f('ix_coils_grade'), table_name='coils')
    op.drop_index(op.f('ix_coils_coil_number'), table_name='coils')
    op.drop_index('idx_coils_grade', table_name='coils')
    op.drop_table('coils')
    op.drop_index(op.f('ix_weight_receipt_drafts_timestamp'), table_name='weight_receipt_drafts')
    op.drop_index(op.f('ix_weight_receipt_drafts_job_card_number'), table_name='weight_receipt_drafts')
    op.drop_index('idx_wrd_job_design', table_name='weight_receipt_drafts')
    op.drop_table('weight_receipt_drafts')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_is_active'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_code'), table_name='vendors')
    op.drop_index('idx_vendors_type', table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_slitting_plans_status'), table_name='slitting_plans')
    op.drop_index(op.f('ix_slitting_plans_plan_id'), table_name='slitting_plans')
    op.drop_table('slitting_plans')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_is_active'), table_name='customers')
    op.drop_index(op.f('ix_customers_code'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_audit_log_user_name'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_table_name'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_record_id'), table_name='audit_log')
    op.drop_index('idx_audit_table_record', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
